name: __PRODUCT_SLUG_UNDERSCORE__
description: "__PRODUCT_DESCRIPTION__"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
